config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get '/auth/:provider/callback' => 'sessions#create'
  get '/signout' => 'sessions#destroy', :as => :signout

  get '/progress' => 'progress_report#index'
  
  resources :cohorts
  resources :homework, only: [:index, :show, :create, :update, :destroy]
  resources :students, only: [:index, :show, :create, :update, :destroy] do
    get :issues, on: :member
    resources :assignments, only: [:index, :show, :create, :update, :destroy]
  end
  resource :user, only: [:show, :update]
end

app/models/cohort.rb
class Cohort < ActiveRecord::Base
  has_many :students
  has_many :homeworks
  has_many :assignments, through: :students

  scope :active, -> { where(is_active: true) }

  def admins_include?(nickname)
    user = User.where(nickname: nickname).first
    client = user ? Octokit::Client.new(access_token: user.access_token) : Octokit
    client.org_members(org, role: 'admin').map(&:login).include?(nickname)
  end

  def seed_homework
    (1..9).each do |week|
      (1..4).each do |day|
        homeworks.create(name: "Assignment #{week}-#{day}")
      end
    end
  end
end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
  before_action :require_authentication
  before_action :set_cohort, only: [:show, :edit, :update, :destroy]

  # GET /cohorts
  # GET /cohorts.json
  def index
    @cohorts = Cohort.all
  end

  # GET /cohorts/1
  # GET /cohorts/1.json
  def show
  end

  # GET /cohorts/new
  def new
    @cohort = Cohort.new
  end

  # GET /cohorts/1/edit
  def edit
  end

  # POST /cohorts
  # POST /cohorts.json
  def create
    @cohort = Cohort.new(cohort_params)

    respond_to do |format|
      if @cohort.save
        format.html { redirect_to @cohort, notice: 'Cohort was successfully created.' }
        format.json { render :show, status: :created, location: @cohort }
      else
        format.html { render :new }
        format.json { render json: @cohort.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cohorts/1
  # PATCH/PUT /cohorts/1.json
  def update
    respond_to do |format|
      if @cohort.update(cohort_params)
        format.html { redirect_to @cohort, notice: 'Cohort was successfully updated.' }
        format.json { render :show, status: :ok, location: @cohort }
      else
        format.html { render :edit }
        format.json { render json: @cohort.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cohorts/1
  # DELETE /cohorts/1.json
  def destroy
    @cohort.destroy
    respond_to do |format|
      format.html { redirect_to cohorts_url, notice: 'Cohort was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cohort
      @cohort = Cohort.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cohort_params
      params[:cohort].permit(:name, :org, :is_active)
    end
end

app/views/cohorts/_form.html.erb
<%= simple_form_for(@cohort) do |f| %>
  <%= f.error_notification %>
  <%= f.input :name %>
  <%= f.input :org %>
  <%= f.input :is_active %>
  <%= f.button :submit %>
<% end %>

app/views/cohorts/edit.html.erb
<div class="page-header">
  <h1>Edit Cohort</h1>
</div>

<%= render 'form' %>

app/views/cohorts/index.html.erb
<div class="page-header">
  <h1>Cohorts</h1>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Org</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cohorts.each do |cohort| %>
      <tr>
        <td><%= link_to cohort.name, cohort %></td>
        <td><%= cohort.org %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cohort', new_cohort_path %>

app/views/cohorts/new.html.erb
<div class="page-header">
  <h1>New Cohort</h1>
</div>

<%= render 'form' %>

app/views/cohorts/show.html.erb
<div class="page-header">
  <h1>Cohort: <%= @cohort.name %></h1>
</div>

<%= link_to 'Edit', edit_cohort_path(@cohort) %><br>
<%= link_to 'Destroy', @cohort, method: :delete, data: { confirm: 'Are you sure?' } %>