config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get '/auth/:provider/callback' => 'sessions#create'
  get '/signout' => 'sessions#destroy', :as => :signout

  get '/progress' => 'progress_report#index'
  
  resources :cohorts
  resources :homework, only: [:index, :show, :create, :update, :destroy]
  resources :students, only: [:index, :show, :create, :update, :destroy] do
    get :issues, on: :member
    resources :assignments, only: [:index, :show, :create, :update, :destroy]
  end
  resource :user, only: [:show, :update]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Grade Book</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/chartist.js/latest/chartist.min.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script src="//cdn.jsdelivr.net/chartist.js/latest/chartist.min.js"></script>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="<%= root_url %>">
            <%= image_tag "icon.png", size: '36x36' %>
          </a>
        </div>
        <ul class="nav navbar-nav"><% if current_user %>
          <li class="<%= "active" if controller_name == "students" %>"><%= link_to "Students", students_path %></li>
          <li class="<%= "active" if controller_name == "homework" %>"><%= link_to "Homework", homework_index_path %></li>
          <li class="<%= "active" if controller_name == "progress_report" %>"><%= link_to "Progress Report", progress_path %></li>
        <% end %></ul>
        <ul class="nav navbar-nav navbar-right">
          <%- if current_user -%>
          <li>
            <span class="navbar-text">
              <img class="avatar" height="20" src="https://avatars1.githubusercontent.com/u/<%= current_user.uid %>?v=3&amp;s=40" width="20">
              <b><%= link_to current_user.nickname, user_path %></b>
            </span>
          </li>
          <li>
            <a href="<%= signout_path %>"><i class="fa fa-lg fa-sign-out"></i></a>
          </li>
          <%- else -%>
            <li>
              <a href="/auth/github"><i class="fa fa-lg fa-github"></i></a>
            </li>
          <%- end -%>
          </li>
        </ul>
      </div><!-- /.container-fluid -->
    </nav>
    <div class="container">
      <%= flash_messages %>
      <%= yield %>
    </div>
    <footer class="footer noprint">
      <div class="container">
        <p><%= image_tag "logo.png", :size => '64x64' %></p>
      </div>
    </footer>
  </body>
</html>